'use client';

import Battlefield from '@/components/Battlefield';
import BattlefieldPlanning from '@/components/BattlefieldPlanning';
import GameSettings from '@/components/GameSettings';
import { GAME_STAGES, GAME_MODE } from '@/libs/config';
import { useEffect, useState } from 'react';

export default function Game() {
  const initialGameSetupState = {
    stage: GAME_STAGES.menu,
    player: {},
    enemy: {},
    mode: GAME_MODE.singlePlayer,
  };
  const [gameSetup, setGameSetup] = useState(initialGameSetupState);

  const onGameModeChange = (mode) => {
    setGameSetup({
      ...gameSetup,
      mode,
      stage: GAME_STAGES.planning,
    });
  };

  const onGameStart = () => {
    setGameSetup({
      ...gameSetup,
      stage: GAME_STAGES.ongoing,
    });
  };

  const onReset = () => {
    setGameSetup({
      ...gameSetup,
      stage: GAME_STAGES.menu,
    });
  };

  useEffect(() => {
    if (
      gameSetup.stage !== GAME_STAGES.ongoing &&
      gameSetup.player.stage === GAME_STAGES.ready &&
      gameSetup.enemy.stage === GAME_STAGES.ready
    ) {
      console.info('Both are ready');
      setGameSetup({
        ...gameSetup,
        stage: GAME_STAGES.ongoing,
      });
    }
  }, [gameSetup, gameSetup.player.stage, gameSetup.enemy.stage]);

  return (
    <div className="flex flex-1 flex-col items-center p-24 h-screen">
      <h1 className="mb-4 text-xl font-extrabold text-gray-900 dark:text-white text-center">
        <span className="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">
          Battle Ships
        </span>{' '}
        multiplayer
      </h1>

      {[GAME_STAGES.planning].includes(gameSetup.stage) ? (
        <div className="w-full flex justify-around">
          <BattlefieldPlanning
            position={1}
            actions={{ onChange: setGameSetup }}
            gameSetup={gameSetup}
          />

          <BattlefieldPlanning
            position={2}
            autoGenerated
            actions={{ onChange: setGameSetup }}
            gameSetup={gameSetup}
          />
        </div>
      ) : null}

      {[GAME_STAGES.ongoing].includes(gameSetup.stage) ? (
        <div className="w-full flex justify-around">
          <Battlefield
            gameState={gameSetup}
            position={1}
            actions={{ onChange: setGameSetup }}
            gameSetup={gameSetup}
          />

          <Battlefield
            gameState={gameSetup}
            position={2}
            autoGenerated
            actions={{ onChange: setGameSetup }}
            gameSetup={gameSetup}
          />
        </div>
      ) : null}

      <GameSettings
        gameSetup={gameSetup}
        actions={{
          onReset,
          onGameModeChange: onGameModeChange,
          onChange: setGameSetup,
          onGameStart: onGameStart,
        }}
      />
    </div>
  );
}
