import { Suspense } from 'react';
import Navbar from '../components/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen overflow-x-hidden`}
        suppressHydrationWarning={true}
      >
        <header>
          <Suspense fallback={<div>Loading...</div>}>
            <Navbar />
          </Suspense>
        </header>
        <div className="flex flex-1 flex-col min-w-min text-slate-50">
          {children}
        </div>
      </body>
    </html>
  );
}
